services:

  kafka:
      image: confluentinc/cp-kafka:latest
      hostname: kafka
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_CLUSTER_ID: "r8Wa9dL_RraPLkJ3bd_Cdg"
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: CONTROLLER://0.0.0.0:29093,INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
        KAFKA_ADVERTISED_LISTENERS: CONTROLLER://kafka:29093,INTERNAL://kafka:29092,EXTERNAL://localhost:9092
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL 
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_MIN_INSYNC_REPLICAS: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_LOG_DIRS: /var/lib/kafka/data
      volumes:
          - ./kafka_data:/var/lib/kafka/data



  producer:
      build: ./producer
      container_name: producer
      depends_on:
        - kafka

      command: ["/bin/sh", "-c", "sleep 5 && spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.0-preview3 --conf spark.jars.ivy=/tmp/.ivy2 --master local[*] /app/producer.py"]  
      restart: always
      volumes:
      - ./producer/customer:/app/customer
      - ./producer/order:/app/order
      - ./producer/spark_producer_checkpoint:/tmp/spark_producer_checkpoint
      - ./producer:/app
      
      

  consumer:
      build: ./consumer
      container_name: consumer
      depends_on:
        - kafka

      command: ["/bin/sh", "-c", "sleep 10 && spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.0-preview3 --conf spark.jars.ivy=/tmp/.ivy2 --master local[*] /app/consumer.py"]  
      restart: always
      volumes:
      - ./consumer:/app
      - ./consumer/spark_consumer_checkpoint:/tmp/spark_consumer_checkpoint

        


      
